-- Fix password hashes for all pre-created accounts
-- Password: admin123 (hash generated by BCryptPasswordEncoder)
UPDATE users SET password_hash = '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6' WHERE username = 'admin';
UPDATE users SET password_hash = '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6' WHERE username = 'totruong';
UPDATE users SET password_hash = '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6' WHERE username = 'ketoan';
