-- Create accounts for household owners
-- Password: 123456 (BCrypt hash generated by application)
-- Hash will be: $2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6

-- Insert users for each household owner
INSERT INTO users(username, password_hash, full_name, phone, email, status, household_id) VALUES
('cudan1', '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6', 'Nguyen Van An', '0901111111', 'nguyenvanan@gmail.com', 'ACTIVE', 1),
('cudan2', '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6', 'Tran Thi Binh', '0902222222', 'tranthibinh@gmail.com', 'ACTIVE', 2),
('cudan3', '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6', 'Le Hoang Cuong', '0903333333', 'lehoangcuong@gmail.com', 'ACTIVE', 3),
('cudan4', '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6', 'Pham Minh Duc', '0904444444', 'phamminhdu@gmail.com', 'ACTIVE', 4),
('cudan5', '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6', 'Hoang Thi Em', '0905555555', 'hoangthiem@gmail.com', 'ACTIVE', 5),
('cudan6', '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6', 'Vo Van Phuc', '0906666666', 'vovanphuc@gmail.com', 'ACTIVE', 6),
('cudan7', '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6', 'Do Thi Giang', '0907777777', 'dothigiang@gmail.com', 'ACTIVE', 7),
('cudan8', '$2a$10$kSWHms1JdJzPI9ft.9DWQO7u6/eA2PSnnI5gLmK9Y2z8HnTAMstq6', 'Bui Van Hung', '0908888888', 'buivanhung@gmail.com', 'ACTIVE', 8);

-- Assign RESIDENT role to all household owners
INSERT INTO user_roles(user_id, role_id)
SELECT u.id, r.id FROM users u, roles r WHERE u.username LIKE 'cudan%' AND r.code = 'RESIDENT';
